# Dependencies
markdown:         redcarpet
hilighter:        pygments

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Multi-Discipline
tagline:          "A generalist maker solving problems in a specialized world."
url:              http://multi-discipline.com
paginate:         5
baseurl:          /
author:
  name:           Jason M. Klug
  url:            https://twitter.com/jasonmklug
  email:          jason@multi-discipline.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jasonmklug/jasonmklug.github.io
  
# Amazon S3
asset_hostname:       multi-discipline.s3.amazonaws.com

# Amazon Affiliate Program
amazon_affiliate_tag:   multidiscipline-20
