# Dependencies
markdown:         redcarpet
hilighter:        pygments

# Permalinks
permalink:        pretty

# Setup
title:            Multi-Discipline
tagline:          "A generalist maker solving problems in a specialized world."
url:              http://multi-discipline.com
paginate:         5
baseurl:          /
author:
  name:           Jason M. Klug
  url:            https://twitter.com/jasonmklug
  email:          jason@multi-discipline.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jasonmklug/jasonmklug.github.io
