# Dependencies
markdown:         kramdown
hilighter:        pygments

# Environment
timezone:         America/Chicago

# Build Process
destination:  public
exclude:      ['README.md', 'public']

# Setup
title:            Multi-Discipline
tagline:          "The Problems and Solutions of a Generalist Maker"
url:              http://multi-discipline.com
paginate:         20
baseurl:          /
permalink:        /:year/:month/:day/:title/
author:
  name:           Jason M. Klug
  url:            https://twitter.com/jasonmklug
  email:          jason@multi-discipline.com
excerpt_separator: <!-- excerpt_separator -->
page_title_array: ["About", "Book Notes", "Recommended Podcasts", "Post Archive"]
plugins: [jekyll-paginate]

# Collections
collections:
  book_notes:
    output: true
    permalink: /book_notes/:path/

# Default YAML Values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: jasonmklug

# Asset Groups
path_to_author_images:  /assets/images/authors/

# Amazon S3
asset_hostname:         multi-discipline.s3.amazonaws.com
path_to_product_images: /images/product/
path_to_post_images:    /images/post/

# Amazon Affiliate Program
amazon_affiliate_tag:   multidiscipline-20

