# Dependencies
markdown:         redcarpet
hilighter:        pygments

# Permalinks
permalink:        pretty

# Setup
title:            Multi-Discipline
tagline:          "A generalist working in a specialized world."
url:              http://multi-discipline.com
paginate:         1
baseurl:          /
author:
  name:           Jason Klug
  url:            https://twitter.com/jasonmklug
  email:          jason@klug.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jasonmklug/jasonmklug.github.io
