# Dependencies
markdown:         redcarpet
hilighter:        pygments

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Multi-Discipline
tagline:          "The Problems and Solutions of a Generalist Maker"
url:              http://multi-discipline.com
paginate:         20
baseurl:          /
author:
  name:           Jason M. Klug
  url:            https://twitter.com/jasonmklug
  email:          jason@multi-discipline.com
excerpt_separator: <end_excerpt>

# Collections
collections:
  book_notes:
    output: true
    permalink: /book_notes/:path/

# Custom vars
github:
  repo:           https://github.com/jasonmklug/multi-discipline
  
# Amazon S3
asset_hostname:       multi-discipline.s3.amazonaws.com

# Amazon Affiliate Program
amazon_affiliate_tag:   multidiscipline-20